newTurple= tuple('ghijkl')
newTurple1= tuple('abcdef')
anew=tuple([11,12,13,14,25])
print(newTurple + newTurple1)
print('---------------------------------------')
print(tuple([1,2,3,4,5]))
print('---------------------------------------')
print(anew)
print('---------------------------------------')
